package penguinDB

import "errors"

var (
	ERR_KEY_IS_EMPTY              = errors.New("THE KEY IS EMPTY")
	ERR_INDEX_UPDATE_FAILED       = errors.New("FAILED TO UPDATE INDEX")
	ERR_KEY_NOT_FOUND             = errors.New("KEY NOT FOUND IN DATABASE")
	ERR_DATA_FILE_NOT_FOUND       = errors.New("DATA FILE IS NOT FOUND")
	ERR_DATA_DIRECTORY_CORRUPTED  = errors.New("THE DATABASE DIRECTORY MAYBE CORRUPTED")
	ERR_EXCEED_MAX_BATCH_NUM      = errors.New("EXCEED THE MAX BATCH NUM")
	ERR_MERGE_IS_PROGRESS         = errors.New("MERGE IS IN PROGRESS, TRY AGAIN LATER")
	ERR_DATABASE_IS_USING         = errors.New("THE DATABASE DIRECTORY IS USED BY ANOTHER PROCESS")
	ERR_MERGE_RATIO_UNREACHED     = errors.New("THE MERGE RATIO DO NOT REACH THE OPTION")
	ERR_NO_ENOUGH_SPACE_FOR_MERGE = errors.New("NO ENOUGH DISK SPACE FOR MERGE")
	ERR_BACKUP_DIR_IS_EMPTY       = errors.New("BACKUP DIRECTORY IS EMPTY")
	ERR_DB_CLOSED                 = errors.New("DATABASE IS CLOSED")
)
